name: Continuous Integration Testing

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      # 1. Menjalankan pengecekan TypeScript (vue-tsc)
      - name: Run Type Check
        run: bun run type-check

      # 2. Menjalankan Unit & Integration Test (Vitest)
      - name: Run Vitest
        run: bun run test
